<?php 

$auto_usate = [
    [
        "id" => 1,
        "marca" => "peugeot",
        "carburante" => "super 95",
        "modello" => "208",
        "anno" => 2013,
        "cilindrata" => 1199,
        "trasmissione" => "manuale",
        "km" => 121055,
        "colore" => "nero",
        "prezzo" => 5890.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control, vetri oscurati, tetto panoramico",
        "nPorte" => 5,
        "localita" => "torino",
        "trazione" => "null",
        "targa" => "null",
        "immagine" => "https://cdn.miacar.it/thumbs/vehicle-gallery-800x560/cars/PEUGEOT/208/BlueHDI_75_5p_Allure/Nero_Perla/8CVTJ/1.png"   
    ],
    [
        "id" => 2,
        "marca" => "bmw",
        "carburante" => "diesel",
        "modello" => "120",
        "anno" => 2010,
        "cilindrata" => 1995,
        "trasmissione" => "semiautomatico",
        "km" => 85000,
        "colore" => "blu",
        "prezzo" => 22000.00,
        "accessori" => "null",
        "nPorte" => 5,
        "localita" => "roma",
        "trazione" => "anteriore",
        "targa" => "ab123gv",
        "immagine" => "https://prod.pictures.autoscout24.net/listing-images/fcee5d12-a521-4710-8bd0-a1704ad9788b_be3a58b7-9c03-4906-a354-75af87ddba81.jpg/640x480.jpg"   
    ],
    [
        "id" => 3,
        "marca" => "fiat",
        "carburante" => "benzina",
        "modello" => "500",
        "anno" => 2010,
        "cilindrata" => 1242,
        "trasmissione" => "manuale",
        "km" => 98000,
        "colore" => "grigio",
        "prezzo" => 5990.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control",
        "nPorte" => 3,
        "localita" => "roma",
        "trazione" => "posteriore",
        "targa" => "null",
        "immagine" => "https://www.fiat.it/content/dam/fiat/cross/models/500-family-2020/500-Sport/Exteriors/Mobile/500-sport-sporty-details-mobile-288x220.jpg"   
    ],
    [
        "id" => 4,
        "marca" => "ford",
        "carburante" => "benzina 91",
        "modello" => "ecosport",
        "anno" => 2018,
        "cilindrata" => 998,
        "trasmissione" => "manuale",
        "km" => 35383,
        "colore" => "bianca",
        "prezzo" => 16900.00,
        "accessori" => "null",
        "nPorte" => 5,
        "localita" => "cagliari",
        "trazione" => "null",
        "targa" => "ab123vg",
        "immagine" => "https://www.fordauthos.it/images/vehicles/3472431/0/large"   
    ],
    [
        "id" => 5,
        "marca" => "ford",
        "carburante" => "benzina",
        "modello" => "mustang",
        "anno" => 2016,
        "cilindrata" => 2261,
        "trasmissione" => "automatico",
        "km" => 101000,
        "colore" => "rosso",
        "prezzo" => 24000.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control, vetri oscurati, tetto panoramico",
        "nPorte" => 2,
        "localita" => "palermo",
        "trazione" => "anteriore",
        "targa" => "sd345gi",
        "immagine" => "https://upload.wikimedia.org/wikipedia/it/6/60/FordMustang6genItalia.JPG"   
    ],
    [
        "id" => 6,
        "marca" => "vw",
        "carburante" => "diesel",
        "modello" => "polo",
        "anno" => 2008,
        "cilindrata" => 1896,
        "trasmissione" => "manuale",
        "km" => 230000,
        "colore" => "nero",
        "prezzo" => 3500.00,
        "accessori" => "alzacristalli elettrici, climatizzatore, cruise control, vetri oscurati, tetto panoramico",
        "nPorte" => 3,
        "localita" => "padova",
        "trazione" => "null",
        "targa" => "ag378ik",
        "immagine" => "https://cdn.miacar.it/thumbs/vehicle-gallery-800x560/cars/VOLKSWAGEN/POLO/1_0_TSI_5p__Comfortline_BMT/Nero_Perla/SNBPS/1.png"   
    ],
]

?>